# Generated by Django 3.2.12 on 2022-04-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('description', models.CharField(max_length=5000, verbose_name='Description')),
                ('position', models.CharField(max_length=255, verbose_name='Position')),
                ('payment', models.CharField(max_length=255, verbose_name='Payment')),
                ('start', models.DateField(verbose_name='Start Date')),
                ('end', models.DateField(verbose_name='End Date')),
                ('restrictions', models.CharField(max_length=5000, verbose_name='Restrictions')),
                ('requirements', models.CharField(max_length=5000, verbose_name='Requirements')),
                ('deadline', models.DateField(verbose_name='Deadline')),
                ('job_img', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Job Image')),
            ],
        ),
    ]
