# Generated by Django 3.2.12 on 2022-02-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('stdid', models.IntegerField()),
                ('major', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
