# Generated by Django 3.2.12 on 2022-04-05 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
