# Generated by Django 3.2.12 on 2022-03-30 06:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('position', models.CharField(max_length=255, verbose_name='Position')),
                ('payment', models.CharField(max_length=255, verbose_name='Payment')),
                ('start', models.DateField(verbose_name='Start Date')),
                ('end', models.DateField(verbose_name='End Date')),
                ('restrictions', ckeditor.fields.RichTextField(verbose_name='Restrictions')),
                ('requirements', ckeditor.fields.RichTextField(verbose_name='Requirements')),
                ('deadline', models.DateField(verbose_name='Deadline')),
                ('job_img', models.ImageField(blank=True, null=True, upload_to='job_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(max_length=255, verbose_name='Major'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stdid',
            field=models.IntegerField(verbose_name='StudentID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(verbose_name='Year'),
        ),
    ]
