# Generated by Django 3.2.12 on 2022-03-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20220330_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(max_length=5000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.CharField(max_length=5000, verbose_name='Requirements'),
        ),
        migrations.AlterField(
            model_name='job',
            name='restrictions',
            field=models.CharField(max_length=5000, verbose_name='Restrictions'),
        ),
    ]
