# Generated by Django 3.2.12 on 2022-04-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=255, verbose_name='First Name')),
                ('lastname', models.CharField(default='', max_length=255, verbose_name='Last Name')),
                ('email', models.CharField(default='', max_length=255, verbose_name='Email')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='Phone')),
                ('stdid', models.IntegerField(blank=True, null=True, verbose_name='StudentID')),
                ('major', models.CharField(default='', max_length=255, verbose_name='Major')),
                ('gpa', models.FloatField(blank=True, null=True, verbose_name='GPA')),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='profile_img/', verbose_name='Profile Image')),
            ],
        ),
    ]
