# Generated by Django 3.2.12 on 2022-03-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20220330_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_img',
            field=models.ImageField(blank=True, null=True, upload_to='job_images/', verbose_name='Job Image'),
        ),
    ]
