# Generated by Django 3.2.12 on 2022-03-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_job_job_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Job Image'),
        ),
    ]
