# Generated by Django 3.2.12 on 2022-04-05 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_student_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='is_active',
            new_name='activated',
        ),
    ]
