# Generated by Django 3.2.12 on 2022-04-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_rename_is_active_student_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(default='', max_length=255, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stdid',
            field=models.CharField(default='', max_length=255, verbose_name='StudentID'),
        ),
    ]
