# Generated by Django 3.2.12 on 2022-04-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20220418_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_online',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Online'),
        ),
        migrations.AddField(
            model_name='job',
            name='is_remote',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Remote'),
        ),
        migrations.AddField(
            model_name='job',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='job',
            name='major',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Major'),
        ),
    ]
