# Generated by Django 3.2.12 on 2022-04-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20220428_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255, verbose_name='Job Title')),
                ('application_date', models.DateField(verbose_name='Application Date')),
                ('firstname', models.CharField(default='', max_length=255, verbose_name='First Name')),
                ('lastname', models.CharField(default='', max_length=255, verbose_name='Last Name')),
                ('email', models.CharField(default='', max_length=255, verbose_name='Email')),
                ('stdid', models.CharField(default='', max_length=255, verbose_name='StudentID')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='Resume')),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to='cover_letters/', verbose_name='Cover Letter')),
                ('transcript', models.FileField(blank=True, null=True, upload_to='transcripts/', verbose_name='Transcript')),
            ],
        ),
    ]
